### ISSUE TITLE
Validate failure

### ISSUE THREAD

**Issue by auridasf** [chainapsis/keplr-chain-registry#751]
Is `validate` supposed to be working? I am getting this even for cosmoshub:

```
yarn validate cosmos/cosmoshub.json
ReferenceError: fetch is not defined
    at /Users/aurifra/VSProjects/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/src/fetch.ts:63:19
    at Generator.next (<anonymous>)
    at /Users/aurifra/VSProjects/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/build/fetch.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/aurifra/VSProjects/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/build/fetch.js:4:12)
    at simpleFetch (/Users/aurifra/VSProjects/keplr-chain-registry/node_modules/@keplr-wallet/simple-fetch/build/fetch.js:48:12)
    at /Users/aurifra/VSProjects/keplr-chain-registry/node_modules/@keplr-wallet/chain-validator/src/connection.ts:38:37
    at Generator.next (<anonymous>)
    at /Users/aurifra/VSProjects/keplr-chain-registry/node_modules/@keplr-wallet/chain-validator/build/connection.js:8:71
    at new Promise (<anonymous>)
Failed to get response /status from rpc endpoint
```

**Comment by editaahn** [comment]
It works on my side. Pull the latest change from `main` branch and try again please?

**Comment by auridasf** [comment]
> It works on my side. Pull the latest change from `main` branch and try again please?

I did it after pulling latest, same thing. Even tried `rm -fr node_modules` and fresh `yarn install`, same thing.

**Comment by editaahn** [comment]
I just can guess it is probably a Node.js version issue since it's not able to refer `fetch`. What version of Node.js are you using?

**Comment by auridasf** [comment]
Thanks, upgrading node to latest stable helped!
